from . import club
from . import coach
from . import evaluation
from . import joueur
from . import reservation
from . import terrain
from . import match
from . import tournoi
from . import abonnes_club
from . import calendrier_club
from . import cassier
from . import manager
from . import res_partner
from . import product
from . import inscri_club
